language: ruby

sudo: false

script: bundle exec rake

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  
gemfile:
  - Gemfile
  - gemfiles/Gemfile-edge
  
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.2
