language: ruby

sudo: false

script: bundle exec rake

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  
gemfile:
  - Gemfile
  - gemfiles/Gemfile-edge
  
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: 2.2

env:
  global:
    - secure: "LFBE3H1FUpPR4yBoMk0R3xGp6pNR/Dn2/PkoUtdoDiLluNL+2LQVQPFYmfWjPYlbsQa8KY94lVT7pP8lfePkXHEJ4CtjoKGVmQjRG4DTNCrSUTuQiw08tIHBiZJCTZHk8ZoAcQ2ac5Sg9JAxjTpjz2CO77yL1XNzlPlSjZObuAc="
    - secure: "euxN9HsbO4tn3W3CXUgMxEQJrDK3kACPrRGbqXnYG55BS5gWiM1V7zpjkKSBNlLFYJQidrT63Jrwr4B/RNmZTl5aRoFdEyIqgsfQKrTENxp2c7E5eXNfXExfXx4rYOw2uXeWYrVsyk24XhOjIioQA/zXhMwXEmBXjJd1uAheRw4="